[project]
name = "dr-copper"
version = "0.1.0"
description = ""
authors = [
    {name = "EgorTglhf",email = "friggi40@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<3.14.1"
dependencies = [
    "jupyter (>=1.1.1,<2.0.0)",
    "jupyterlab (>=4.5.7,<5.0.0)",
    "ipykernel (>=7.2.0,<8.0.0)",
    "pandas (>=3.0.3,<4.0.0)",
    "numpy (>=2.4.6,<3.0.0)",
    "scipy (>=1.17.1,<2.0.0)",
    "statsmodels (>=0.14.6,<0.15.0)",
    "arch (>=8.0.0,<9.0.0)",
    "scikit-learn (>=1.8.0,<2.0.0)",
    "xgboost (>=3.2.0,<4.0.0)",
    "quantstats (>=0.0.81,<0.0.82)",
    "backtrader (>=1.9.78.123,<2.0.0.0)",
    "quantlib-python (>=1.18,<2.0)",
    "plotly (>=6.7.0,<7.0.0)",
    "nbconvert (>=7.17.1,<8.0.0)",
    "torch (>=2.12.0,<3.0.0)",
    "torchvision (>=0.27.0,<0.28.0)",
    "torchaudio (>=2.11.0,<3.0.0)"
]

[tool.poetry]
packages = [{include = "dr_copper", from = "src"}]

[tool.poetry.dependencies]
torch = {source = "pytorch-gpu"}
torchvision = {source = "pytorch-gpu"}
torchaudio = {source = "pytorch-gpu"}
[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu130"
priority = "explicit"

[dependency-groups]
dev = [
    "pytest (>=9.0.3,<10.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "ruff (>=0.15.13,<0.16.0)",
    "ipdb (>=0.13.13,<0.14.0)",
    "pre-commit (>=4.6.0,<5.0.0)"
]
